<?php
/**
 * Created by PhpStorm.
 * User: liyulin
 * Date: 2017-03-24
 * Time: 17:28
 */
namespace Admin\Controller;
use Think\Controller;
class VideoController extends BaseController{
    protected $model;
    protected $logic;
    public function __construct(){
        parent::__construct();
        $this->model = D('Video');
        $this->logic = A("Video","Logic");
    }

    public function index(){
        $this->logic->get_videos();
        $this->display();
    }

    public function add_qiniu(){
        $this->assign("domain",C("QINIU_DOMAIN"));
        $this->assign("webId",$_SESSION['webInfo']['id']);
        $qiniu = A("Qiniu","Logic");
        $qiniu->get_token();
        $this->display();
    }

    public function save_qiniu(){
        $this->logic->save();
    }

    public function edit()
    {
        return parent::edit(); // TODO: Change the autogenerated stub
    }

    public function save_info(){
        $this->logic->edit_video();
    }

    public function del(){
        $ids = I("id",0);
        if($ids==0)echo show(300,"id错误");
        $res = $this->model->where("id in ($ids)")->setField("is_delete",1);
        if($res !== false){
            echo show(200,"删除成功！");
        }else{
            echo show(300,"删除失败！");
        }
    }
}